master_addr: localhost
master_port: ${now:%H%M%S}
backend: "nccl"
gpus: 1
rank: 1
apex_opt: 'O0'
only_test: False
metric: 'val_loss'
pretrained_head: False

defaults:
  - dataset: coco
  - backbone : darknet53
  - yolo: head 
  - optimizer: sgd 
  - experiment: experiment
  - hydra/launcher: basic 
    


hydra:
  run:
    dir: output/${experiment.name}
  sweep:
    dir: output/${experiment.name}
    subdir: ./
