master_addr: localhost
master_port: ${now:%H%M%S}
backend: "nccl"
gpus: 1
rank: 0
apex_opt: 'O0'
only_test: False
metric: 'val_loss'
batch_norm_sync: False
multiscale: 0
resume: False
pretrained_head: False
verbose: False
track_epoch: False
freq: 10

defaults:
  - dataset: coco
  - backbone : darknet53
  - yolo: head 
  - optimizer: sgd
  - scheduler: step  
  - experiment: experiment
  - hydra/launcher: basic 
    


hydra:
  run:
    dir: output/${experiment.name}
  sweep:
    dir: output/${experiment.name}
    subdir: ./
