# @package hydra.sweeper
_target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper

ax_config:

  # max_trials is application-specific. Tune it for your use case
  max_trials: 100

  experiment:
    # Default to minimize, set to false to maximize
    minimize: ${minimize}

  early_stop:
    # Number of epochs without a significant improvement from
    # the currently known best parameters
    # An Epoch is defined as a batch of trials executed in parallel
    max_epochs_without_improvement: 10

  params:
    yolo.lambda_xy:
      type: range
      bounds: [0.0, 2.0]
    yolo.lambda_wh:
      type: range
      bounds: [0.0, 2.0]
    yolo.lambda_iou:
      type: range
      bounds: [0.0, 2.0]
    yolo.iou_type:
      type: choice 
      values : [1,2,3]
    yolo.lambda_cls:
      type: range
      bounds: [5.0, 20.0]
    yolo.class_loss:
      type: choice 
      values : [0,1]
    # yolo.ignore_threshold:
    #   type: range
    #   bounds: [0.1, 0.9]
    # yolo.lambda_conf:
    #   type: range
    #   bounds: [0.0, 2.0]
    # yolo.lambda_no_conf:
    #   type: range
    #   bounds: [0.0, 1]
    # yolo.alpha:
    #   type: range
    #   bounds: [0.0, 1.0]
    # yolo.gamma:
    #   type: range
    #   bounds: [0.0, 3.0]
    optimizer.weight_decay:
      type: range
      bounds: [0.0,0.001]
    # multiscaler.broadcast:
    #   type: choice 
    #   values : [True,False]


    